import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Standup Randomizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="corporate">
      <body className="antialiased">{children}</body>
    </html>
  );
}

export const dynamic = "force-dynamic";
